# -*- coding: utf-8 -*-
"""Geração de categorias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iJaArcpBIc6Qq4QqCV_vh1le51DT06zy
"""

# Instalar pacote
!pip install spotipy

# Importar pacotes e funções
import spotipy
import spotipy.util as util
from spotipy.oauth2 import SpotifyClientCredentials

# Client id
cid = '3a341a4b68a243478346541d2efd4c9c'

# Client Secret
secret = '0ba44167c53f4e5db45d7bef4302cd93'

# Criar credencial
client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret) 

# Salvar credencial
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

# 50 Categorias no brasil
cat = sp.categories(country="BR", locale="pt_BR", limit=50, offset=0)

# Loop para trazer todas as categorias
itens = list(range(49))

for i in itens:
    print("'" + cat['categories']['items'][i]['id']+"', " )
    # print(i)

cat['categories']['items'][1]

